### ISSUE TITLE
Annotations are ignored while executing tutor k8s start caddy

### ISSUE THREAD

**Issue by g-vijayvergia** [overhangio/tutor#879] opened 2023-07-27 08:19 UTC
**Bug description**

Annotations are not being processed by tutor in Kubernetes env. Refer to annotations section [here](https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations/).

**How to reproduce**

Set the following annotations as part of the Kubernetes service.yml and deploy tutor via OKE service in oracle cloud.

```
apiVersion: v1
kind: Service
metadata:
  name: caddy
  labels:
    app.kubernetes.io/name: caddy
    app.kubernetes.io/component: loadbalancer
  annotations:
    oci.oraclecloud.com/load-balancer-type: "lb"
    service.beta.kubernetes.io/oci-load-balancer-shape: "flexible"
    service.beta.kubernetes.io/oci-load-balancer-shape-flex-min: "10"
    service.beta.kubernetes.io/oci-load-balancer-shape-flex-max: "100"
    service.beta.kubernetes.io/oci-load-balancer-ssl-ports: "443"
    service.beta.kubernetes.io/oci-load-balancer-tls-secret: ssl-certificate-secret
```

The annotations section is ignored by tutor while executing tutor k8s start. It will create a standard load balancer with wrong type and there will be no ssl certificate is configured on Load Balancer even though it is being explicitly passed via the annotations.

**Environment**
Oracle Cloud (OKE service)

**Comment by regisb** [comment] 2023-07-31 07:20
I'm not sure I understand the issue you are facing. Are the annotations not applied, or do they not have the consequences that you expected? Also, you did not explain how you created the annotations (via a plugin? editing the services.yml template?) nor how you applied them (which command did you run?).

I'm going to close this issue because it very much looks like a support request, and not a bug report. Please open a discussion topic on the official Open edX forum: https://discuss.openedx.org/ Also, please read the following: https://docs.tutor.overhang.io/troubleshooting.html

Feel free to re-open if there is indeed a bug in Tutor.

**Closed by regisb** 2023-07-31 07:20 UTC
