### ISSUE TITLE
mySQL 8 permissions problem

### ISSUE THREAD

**Issue by heitara** [overhangio/tutor#888] opened 2023-08-09 10:42 UTC
**Bug description**

When starting the following command:
```bash
tutor local launch
```

The `tutor_local-mysql` container can't be properly initialized.

```
✔ Container tutor_local-mysql-1  Running                                                                                               0.0s 
Initialising MySQL...
mysql: [Warning] Using a password on the command line interface can be insecure.
ERROR 1130 (HY000): Host '172.18.0.13' is not allowed to connect to this MySQL server
    [1/10] Waiting for MySQL service (this may take a while)...
mysql: [Warning] Using a password on the command line interface can be insecure.
ERROR 1130 (HY000): Host '172.18.0.13' is not allowed to connect to this MySQL server
    [2/10] Waiting for MySQL service (this may take a while)...
mysql: [Warning] Using a password on the command line interface can be insecure.
ERROR 1130 (HY000): Host '172.18.0.13' is not allowed to connect to this MySQL server
    [3/10] Waiting for MySQL service (this may take a while)...
mysql: [Warning] Using a password on the command line interface can be insecure.
ERROR 1130 (HY000): Host '172.18.0.13' is not allowed to connect to this MySQL server
    [4/10] Waiting for MySQL service (this may take a while)...
mysql: [Warning] Using a password on the command line interface can be insecure.
ERROR 1130 (HY000): Host '172.18.0.13' is not allowed to connect to this MySQL server
    [5/10] Waiting for MySQL service (this may take a while)...
mysql: [Warning] Using a password on the command line interface can be insecure.
ERROR 1130 (HY000): Host '172.18.0.13' is not allowed to connect to this MySQL server
    [6/10] Waiting for MySQL service (this may take a while)...
mysql: [Warning] Using a password on the command line interface can be insecure.
ERROR 1130 (HY000): Host '172.18.0.13' is not allowed to connect to this MySQL server
    [7/10] Waiting for MySQL service (this may take a while)...
mysql: [Warning] Using a password on the command line interface can be insecure.
ERROR 1130 (HY000): Host '172.18.0.13' is not allowed to connect to this MySQL server
    [8/10] Waiting for MySQL service (this may take a while)...
mysql: [Warning] Using a password on the command line interface can be insecure.
ERROR 1130 (HY000): Host '172.18.0.13' is not allowed to connect to this MySQL server
    [9/10] Waiting for MySQL service (this may take a while)...
mysql: [Warning] Using a password on the command line interface can be insecure.
ERROR 1130 (HY000): Host '172.18.0.13' is not allowed to connect to this MySQL server
    [10/10] Waiting for MySQL service (this may take a while)...
MySQL initialisation error
Error: Command failed with status 1: docker compose -f /Users/emilatanasov/Library/Application Support/tutor/env/local/docker-compose.yml -f /Users/emilatanasov/Library/Application Support/tutor/env/local/docker-compose.prod.yml --project-name tutor_local -f /Users/emilatanasov/Library/Application Support/tutor/env/local/docker-compose.jobs.yml run --rm mysql-job sh -e -c echo "Initialising MySQL..."
mysql_connection_max_attempts=10
mysql_connection_attempt=0
....
```

**How to reproduce**

Be sure to start from scratch and that the mysql container is using version 8.0+.

**Environment**

MacOS 13.4.1 - Intel based macbook pro

**Additional context**

Here is a workaround, that should be added to the `mysql` scripts.

Initially the root user has no password, which means the following command works on that container:
```sql
mysql -u root -e "CREATE USER 'root'@'%' IDENTIFIED BY '$MYSQL_ROOT_PASSWORD';"
mysql -u root -e "GRANT ALL PRIVILEGES ON *.* TO 'root'@'%' WITH GRANT OPTION;"
```
Here are the raw SQL statements that can be executed manually on the container.
```sql
CREATE USER 'root'@'%' IDENTIFIED BY 'MYSQL_ROOT_PASSWORD';
GRANT ALL PRIVILEGES ON *.* TO 'root'@'%' WITH GRANT OPTION;
```

**Comment by regisb** [comment] 2023-08-14 14:18
The mysql container should be properly initialised, and the root user created with all the right credentials. What are the logs coming from your mysql container? `tutor local logs mysql`

**Comment by heitara** [comment] 2023-08-14 21:02
I don't see anything specific. The last line of the log shows my manual actions in which I'm executing the commands above.
```text
tutor_local-mysql-1  | 2023-08-08 23:54:55+00:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 8.0.33-1.el8 started.
tutor_local-mysql-1  | '/var/lib/mysql/mysql.sock' -> '/var/run/mysqld/mysqld.sock'
tutor_local-mysql-1  | 2023-08-08T23:54:57.721394Z 0 [Warning] [MY-011068] [Server] The syntax '--skip-host-cache' is deprecated and will be removed in a future release. Please use SET GLOBAL host_cache_size=0 instead.
tutor_local-mysql-1  | 2023-08-08T23:54:57.728883Z 0 [System] [MY-010116] [Server] /usr/sbin/mysqld (mysqld 8.0.33) starting as process 1
tutor_local-mysql-1  | 2023-08-08T23:54:57.732173Z 0 [Warning] [MY-013242] [Server] --character-set-server: 'utf8' is currently an alias for the character set UTF8MB3, but will be an alias for UTF8MB4 in a future release. Please consider using UTF8MB4 in order to be unambiguous.
tutor_local-mysql-1  | 2023-08-08T23:54:57.732192Z 0 [Warning] [MY-013244] [Server] --collation-server: 'utf8mb3_general_ci' is a collation of the deprecated character set UTF8MB3. Please consider using UTF8MB4 with an appropriate collation instead.
tutor_local-mysql-1  | 2023-08-08T23:54:57.742554Z 0 [Warning] [MY-010159] [Server] Setting lower_case_table_names=2 because file system for /var/lib/mysql/ is case insensitive
tutor_local-mysql-1  | 2023-08-08T23:54:57.786620Z 1 [System] [MY-013576] [InnoDB] InnoDB initialization has started.
tutor_local-mysql-1  | 2023-08-08T23:54:58.574967Z 1 [System] [MY-013577] [InnoDB] InnoDB initialization has ended.
tutor_local-mysql-1  | 2023-08-08T23:54:58.999814Z 0 [Warning] [MY-010068] [Server] CA certificate ca.pem is self signed.
tutor_local-mysql-1  | 2023-08-08T23:54:59.000044Z 0 [System] [MY-013602] [Server] Channel mysql_main configured to support TLS. Encrypted connections are now supported for this channel.
tutor_local-mysql-1  | 2023-08-08T23:54:59.009006Z 0 [Warning] [MY-011810] [Server] Insecure configuration for --pid-file: Location '/var/run/mysqld' in the path is accessible to all OS users. Consider choosing a different directory.
tutor_local-mysql-1  | 2023-08-08T23:54:59.077234Z 0 [System] [MY-011323] [Server] X Plugin ready for connections. Bind-address: '::' port: 33060, socket: /var/run/mysqld/mysqlx.sock
tutor_local-mysql-1  | 2023-08-08T23:54:59.078290Z 0 [System] [MY-010931] [Server] /usr/sbin/mysqld: ready for connections. Version: '8.0.33'  socket: '/var/run/mysqld/mysqld.sock'  port: 3306  MySQL Community Server - GPL.
tutor_local-mysql-1  | 2023-08-09T00:00:10.693349Z 0 [System] [MY-013172] [Server] Received SHUTDOWN from user <via user signal>. Shutting down mysqld (Version: 8.0.33).
tutor_local-mysql-1  | 2023-08-09T00:00:11.114883Z 0 [System] [MY-010910] [Server] /usr/sbin/mysqld: Shutdown complete (mysqld 8.0.33)  MySQL Community Server - GPL.
tutor_local-mysql-1  | 2023-08-09 00:02:17+00:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 8.0.33-1.el8 started.
tutor_local-mysql-1  | '/var/lib/mysql/mysql.sock' -> '/var/run/mysqld/mysqld.sock'
tutor_local-mysql-1  | 2023-08-09T00:02:18.274482Z 0 [Warning] [MY-011068] [Server] The syntax '--skip-host-cache' is deprecated and will be removed in a future release. Please use SET GLOBAL host_cache_size=0 instead.
tutor_local-mysql-1  | 2023-08-09T00:02:18.280028Z 0 [System] [MY-010116] [Server] /usr/sbin/mysqld (mysqld 8.0.33) starting as process 1
tutor_local-mysql-1  | 2023-08-09T00:02:18.281703Z 0 [Warning] [MY-013242] [Server] --character-set-server: 'utf8' is currently an alias for the character set UTF8MB3, but will be an alias for UTF8MB4 in a future release. Please consider using UTF8MB4 in order to be unambiguous.
tutor_local-mysql-1  | 2023-08-09T00:02:18.281713Z 0 [Warning] [MY-013244] [Server] --collation-server: 'utf8mb3_general_ci' is a collation of the deprecated character set UTF8MB3. Please consider using UTF8MB4 with an appropriate collation instead.
tutor_local-mysql-1  | 2023-08-09T00:02:18.285505Z 0 [Warning] [MY-010159] [Server] Setting lower_case_table_names=2 because file system for /var/lib/mysql/ is case insensitive
tutor_local-mysql-1  | 2023-08-09T00:02:18.301059Z 1 [System] [MY-013576] [InnoDB] InnoDB initialization has started.
tutor_local-mysql-1  | 2023-08-09T00:02:19.046528Z 1 [System] [MY-013577] [InnoDB] InnoDB initialization has ended.
tutor_local-mysql-1  | 2023-08-09T00:02:19.514178Z 0 [Warning] [MY-010068] [Server] CA certificate ca.pem is self signed.
tutor_local-mysql-1  | 2023-08-09T00:02:19.514577Z 0 [System] [MY-013602] [Server] Channel mysql_main configured to support TLS. Encrypted connections are now supported for this channel.
tutor_local-mysql-1  | 2023-08-09T00:02:19.525005Z 0 [Warning] [MY-011810] [Server] Insecure configuration for --pid-file: Location '/var/run/mysqld' in the path is accessible to all OS users. Consider choosing a different directory.
tutor_local-mysql-1  | 2023-08-09T00:02:19.576795Z 0 [System] [MY-011323] [Server] X Plugin ready for connections. Bind-address: '::' port: 33060, socket: /var/run/mysqld/mysqlx.sock
tutor_local-mysql-1  | 2023-08-09T00:02:19.576946Z 0 [System] [MY-010931] [Server] /usr/sbin/mysqld: ready for connections. Version: '8.0.33'  socket: '/var/run/mysqld/mysqld.sock'  port: 3306  MySQL Community Server - GPL.
tutor_local-mysql-1  | 2023-08-09T00:14:37.400415Z 0 [System] [MY-013172] [Server] Received SHUTDOWN from user <via user signal>. Shutting down mysqld (Version: 8.0.33).
tutor_local-mysql-1  | 2023-08-09T00:14:37.848876Z 0 [System] [MY-010910] [Server] /usr/sbin/mysqld: Shutdown complete (mysqld 8.0.33)  MySQL Community Server - GPL.
tutor_local-mysql-1  | 2023-08-09 10:04:13+00:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 8.0.33-1.el8 started.
tutor_local-mysql-1  | '/var/lib/mysql/mysql.sock' -> '/var/run/mysqld/mysqld.sock'
tutor_local-mysql-1  | 2023-08-09T10:04:14.680072Z 0 [Warning] [MY-011068] [Server] The syntax '--skip-host-cache' is deprecated and will be removed in a future release. Please use SET GLOBAL host_cache_size=0 instead.
tutor_local-mysql-1  | 2023-08-09T10:04:14.687193Z 0 [System] [MY-010116] [Server] /usr/sbin/mysqld (mysqld 8.0.33) starting as process 1
tutor_local-mysql-1  | 2023-08-09T10:04:14.689724Z 0 [Warning] [MY-013242] [Server] --character-set-server: 'utf8' is currently an alias for the character set UTF8MB3, but will be an alias for UTF8MB4 in a future release. Please consider using UTF8MB4 in order to be unambiguous.
tutor_local-mysql-1  | 2023-08-09T10:04:14.689735Z 0 [Warning] [MY-013244] [Server] --collation-server: 'utf8mb3_general_ci' is a collation of the deprecated character set UTF8MB3. Please consider using UTF8MB4 with an appropriate collation instead.
tutor_local-mysql-1  | 2023-08-09T10:04:14.693244Z 0 [Warning] [MY-010159] [Server] Setting lower_case_table_names=2 because file system for /var/lib/mysql/ is case insensitive
tutor_local-mysql-1  | 2023-08-09T10:04:14.723340Z 1 [System] [MY-013576] [InnoDB] InnoDB initialization has started.
tutor_local-mysql-1  | 2023-08-09T10:04:15.638408Z 1 [System] [MY-013577] [InnoDB] InnoDB initialization has ended.
tutor_local-mysql-1  | 2023-08-09T10:04:16.208965Z 0 [Warning] [MY-010068] [Server] CA certificate ca.pem is self signed.
tutor_local-mysql-1  | 2023-08-09T10:04:16.209200Z 0 [System] [MY-013602] [Server] Channel mysql_main configured to support TLS. Encrypted connections are now supported for this channel.
tutor_local-mysql-1  | 2023-08-09T10:04:16.219870Z 0 [Warning] [MY-011810] [Server] Insecure configuration for --pid-file: Location '/var/run/mysqld' in the path is accessible to all OS users. Consider choosing a different directory.
tutor_local-mysql-1  | 2023-08-09T10:04:16.294205Z 0 [System] [MY-011323] [Server] X Plugin ready for connections. Bind-address: '::' port: 33060, socket: /var/run/mysqld/mysqlx.sock
tutor_local-mysql-1  | 2023-08-09T10:04:16.294684Z 0 [System] [MY-010931] [Server] /usr/sbin/mysqld: ready for connections. Version: '8.0.33'  socket: '/var/run/mysqld/mysqld.sock'  port: 3306  MySQL Community Server - GPL.
tutor_local-mysql-1  | 2023-08-09T10:05:44.328775Z 20 [Warning] [MY-013360] [Server] Plugin sha256_password reported: ''sha256_password' is deprecated and will be removed in a future release. Please use caching_sha2_password instead'```
Then after another restart of the docker containers using `tutor` tool all the scripts that should populate the DB were properly executed (no obvious errors).

**Comment by heitara** [comment] 2023-08-14 21:18
I think it might be related to the new [SHA authentication plugin](https://dev.mysql.com/doc/refman/8.0/en/sha256-pluggable-authentication.html). Also something strange - initially I wasn't able to authenticate using the generated password. The password wasn't required, similar to what's the default behavior of mysql. 
> In short, I had to create my root@* user manually using the generated password, so all other containers can access the DB with it.

**Comment by regisb** [comment] 2023-08-15 14:01
Can you consistently reproduce the issue on your computer?

**Comment by delbra1n** [comment] 2023-09-09 10:16
Same problem for me and apperently other people too: https://discuss.openedx.org/t/host-172-18-0-13-is-not-allowed-to-connect-to-this-mysql-server/9118

**Comment by delbra1n** [comment] 2023-09-09 10:18
I found out that apparently the services start simultaneously instead of one after the other and that this is causing the problem

**Comment by regisb** [comment] 2023-09-22 12:03
@heitara can you still reproduce the issue with the recent upgrade to mysql 8.1.0 in tutor v16.1.1?

**Comment by delbra1n** [comment] 2023-09-22 16:16
> @heitara can you still reproduce the issue with the recent upgrade to mysql 8.1.0 in tutor v16.1.1?

I am facing the Issue on v16.1.1

**Comment by heitara** [comment] 2023-09-22 19:43
I'll try now.

**Comment by heitara** [comment] 2023-09-22 20:01
To do a proper test I would prefer to try on completely new machine. 
On mine, I can't reproduce it. (The docker keeps some images and the launch takes less than 3 minutes. Starting from scratch took more than that ~ 20 min)
I'm running - tutor, version 16.0.3.
I've removed the mysql docker image and tried once more with the very same command `tutor local launch` and it works.

**Comment by delbra1n** [comment] 2023-09-22 20:39
> To do a proper test I would prefer to try on completely new machine. 
> 
> On mine, I can't reproduce it. (The docker keeps some images and the launch takes less than 3 minutes. Starting from scratch took more than that ~ 20 min)
> 
> I'm running - tutor, version 16.0.3.
> 
> I've removed the mysql docker image and tried once more with the very same command `tutor local launch` and it works.

How dis you fix it?

**Comment by regisb** [comment] 2023-09-25 09:03
I'm going to close this for now. If you are still facing this issue, please open a new topic on the [Open edX forum](https://discuss.openedx.org/).

- Include your tutor version.
- Explain whether you are running an upgrade or creating a new platform from scratch.
- What command are you running?
- Include mysql logs (`tutor local logs mysql`).

**Closed by regisb** 2023-09-25 09:03 UTC

**Comment by guerrerocarlos** [comment] 2024-07-04 13:25
Had the same issue, probably caused by an incomplete first attempt due to RAM less than 4GB.

To fix it:

Erase all local images and volumes doing:

```
docker stop $(docker ps -aq)
docker rm $(docker ps -aq)
docker rmi $(docker images -q)
docker volume prune -f
docker network prune -f
```

And then deleting all the existing tutor configuration and local files 

`
rm -rf ~/.local/share/tutor
`

Then tried again from scratch and the issue was gone.
