### ISSUE TITLE
'Could not create directory for saving email messages: /edx/src/ace_messages' in development

### ISSUE THREAD

**Issue by PavlosIsaris** [overhangio/tutor#316] opened 2020-04-09 08:58 UTC
**Bug description**

When trying to register a new user, I get the following error in the log console:

```
'Could not create directory for saving email messages: %s (%s)' % (self.file_path, err)
lms_1             | ImproperlyConfigured: Could not create directory for saving email messages: /edx/src/ace_messages ([Errno 13] Permission denied: '/edx')

```

I tried to create the `/edx` directory in the `tutor` root directory as followed:
```
sudo mkdir $(tutor config printroot)/edx && sudo chown -R user:user $(tutor config printroot)/edx
```

But the error still persists. Any ideas of what I am doing wrong?

**How to reproduce**

Run dev server with `tutor dev start` and try to register a new user to the LMS platform.

**Environment**

Ubuntu 18.04
tutor, version 3.11.6

**Additional context**

**Comment by regisb** [comment] 2020-04-13 17:35
Closing as duplicate of #315

**Closed by regisb** 2020-04-13 17:35 UTC
